package it_academy;

public interface ConstantContainer {

	int COUNT_OF_STUDENTS_OF_EACH_TYPE = 3;
	double MIN_TALENT_OF_STUDENTS = 0.1;
	double MAX_TALENT_OF_STUDENTS = 1.0;
	int ACCURACY_OF_TALENT_CALCULATIONS = 10;

	int X_LENGTH_OF_EDUCATIONAL_PROCESS_FOR_TYPE_1 = 1;
	int X_LENGTH_OF_EDUCATIONAL_PROCESS_FOR_TYPE_2 = 2;
	int X_LENGTH_OF_EDUCATIONAL_PROCESS_FOR_TYPE_3 = 3;

	int COUNT_OF_DIFFERENT_PROCESS_FOR_1_TYPE = 3;
	int COUNT_OF_DIFFERENT_PROCESS_FOR_2_TYPE = 2;
	int COUNT_OF_DIFFERENT_PROCESS_FOR_3_TYPE = 1;

	int TOTAL_LENGTH_OF_EDUCATION_PROCESS_FOR_TYPE_1_AND_TALENT_1 = 198;


}
